local C = KkthnxUI[2]

-- Thanks to ElvUI for providing great textures
local GetEmojiMedia = "Interface\\Addons\\KkthnxUI\\Media\\Chat\\Emojis\\"

local GetEmojiTexture = {
	Angry = GetEmojiMedia .. "Angry.tga",
	Blush = GetEmojiMedia .. "Blush.tga",
	BrokenHeart = GetEmojiMedia .. "BrokenHeart.tga",
	CallMe = GetEmojiMedia .. "CallMe.tga",
	Cry = GetEmojiMedia .. "Cry.tga",
	Facepalm = GetEmojiMedia .. "Facepalm.tga",
	Grin = GetEmojiMedia .. "Grin.tga",
	Heart = GetEmojiMedia .. "Heart.tga",
	HeartEyes = GetEmojiMedia .. "HeartEyes.tga",
	Joy = GetEmojiMedia .. "Joy.tga",
	Kappa = GetEmojiMedia .. "Kappa.tga",
	Meaw = GetEmojiMedia .. "Meaw.tga",
	MiddleFinger = GetEmojiMedia .. "MiddleFinger.tga",
	Murloc = GetEmojiMedia .. "Murloc.tga",
	OkHand = GetEmojiMedia .. "OkHand.tga",
	OpenMouth = GetEmojiMedia .. "OpenMouth.tga",
	Poop = GetEmojiMedia .. "Poop.tga",
	Rage = GetEmojiMedia .. "Rage.tga",
	SadKitty = GetEmojiMedia .. "SadKitty.tga",
	Scream = GetEmojiMedia .. "Scream.tga",
	ScreamCat = GetEmojiMedia .. "ScreamCat.tga",
	SemiColon = GetEmojiMedia .. "SemiColon.tga",
	SlightFrown = GetEmojiMedia .. "SlightFrown.tga",
	Smile = GetEmojiMedia .. "Smile.tga",
	Smirk = GetEmojiMedia .. "Smirk.tga",
	Sob = GetEmojiMedia .. "Sob.tga",
	StuckOutTongue = GetEmojiMedia .. "StuckOutTongue.tga",
	StuckOutTongueClosedEyes = GetEmojiMedia .. "StuckOutTongueClosedEyes.tga",
	Sunglasses = GetEmojiMedia .. "Sunglasses.tga",
	Thinking = GetEmojiMedia .. "Thinking.tga",
	ThumbsUp = GetEmojiMedia .. "ThumbsUp.tga",
	Wink = GetEmojiMedia .. "Wink.tga",
	ZZZ = GetEmojiMedia .. "ZZZ.tga",
}

-- EMOJI EXPRESSION MAPS
C.SetEmojiTexture = {
	-- new keys
	[":angry:"] = GetEmojiTexture.Angry,
	[":blush:"] = GetEmojiTexture.Blush,
	[":broken_heart:"] = GetEmojiTexture.BrokenHeart,
	[":call_me:"] = GetEmojiTexture.CallMe,
	[":cry:"] = GetEmojiTexture.Cry,
	[":facepalm:"] = GetEmojiTexture.Facepalm,
	[":grin:"] = GetEmojiTexture.Grin,
	[":heart:"] = GetEmojiTexture.Heart,
	[":heart_eyes:"] = GetEmojiTexture.HeartEyes,
	[":joy:"] = GetEmojiTexture.Joy,
	[":kappa:"] = GetEmojiTexture.Kappa,
	[":middle_finger:"] = GetEmojiTexture.MiddleFinger,
	[":murloc:"] = GetEmojiTexture.Murloc,
	[":ok_hand:"] = GetEmojiTexture.OkHand,
	[":open_mouth:"] = GetEmojiTexture.OpenMouth,
	[":poop:"] = GetEmojiTexture.Poop,
	[":rage:"] = GetEmojiTexture.Rage,
	[":sadkitty:"] = GetEmojiTexture.SadKitty,
	[":scream:"] = GetEmojiTexture.Scream,
	[":scream_cat:"] = GetEmojiTexture.ScreamCat,
	[":slight_frown:"] = GetEmojiTexture.SlightFrown,
	[":slight_smile:"] = GetEmojiTexture.SlightSmile,
	[":smile:"] = GetEmojiTexture.Smile,
	[":smirk:"] = GetEmojiTexture.Smirk,
	[":sob:"] = GetEmojiTexture.Sob,
	[":sunglasses:"] = GetEmojiTexture.Sunglasses,
	[":thinking:"] = GetEmojiTexture.Thinking,
	[":thumbs_up:"] = GetEmojiTexture.ThumbsUp,
	[":semi_colon:"] = GetEmojiTexture.SemiColon,
	[":wink:"] = GetEmojiTexture.Wink,
	[":zzz:"] = GetEmojiTexture.ZZZ,
	[":stuck_out_tongue:"] = GetEmojiTexture.StuckOutTongue,
	[":stuck_out_tongue_closed_eyes:"] = GetEmojiTexture.StuckOutTongueClosedEyes,

	-- Darth's keys
	[":meaw:"] = GetEmojiTexture.Meaw,

	-- Simpy's keys
	[">:%("] = GetEmojiTexture.Rage,
	[":%$"] = GetEmojiTexture.Blush,
	["<\\3"] = GetEmojiTexture.BrokenHeart,
	[":'%)"] = GetEmojiTexture.Joy,
	[";'%)"] = GetEmojiTexture.Joy,
	[",,!,,"] = GetEmojiTexture.MiddleFinger,
	["D:<"] = GetEmojiTexture.Rage,
	[":o3"] = GetEmojiTexture.ScreamCat,
	["XP"] = GetEmojiTexture.StuckOutTongueClosedEyes,
	["8%-%)"] = GetEmojiTexture.Sunglasses,
	["8%)"] = GetEmojiTexture.Sunglasses,
	[":%+1:"] = GetEmojiTexture.ThumbsUp,
	[":;:"] = GetEmojiTexture.SemiColon,
	[";o;"] = GetEmojiTexture.Sob,

	-- old keys
	[":%-@"] = GetEmojiTexture.Angry,
	[":@"] = GetEmojiTexture.Angry,
	[":%-%)"] = GetEmojiTexture.SlightSmile,
	[":%)"] = GetEmojiTexture.SlightSmile,
	[":D"] = GetEmojiTexture.Smile,
	[":%-D"] = GetEmojiTexture.Smile,
	[";%-D"] = GetEmojiTexture.Grin,
	[";D"] = GetEmojiTexture.Grin,
	["=D"] = GetEmojiTexture.Grin,
	["xD"] = GetEmojiTexture.Grin,
	["XD"] = GetEmojiTexture.Grin,
	[":%-%("] = GetEmojiTexture.SlightFrown,
	[":%("] = GetEmojiTexture.SlightFrown,
	[":o"] = GetEmojiTexture.OpenMouth,
	[":%-o"] = GetEmojiTexture.OpenMouth,
	[":%-O"] = GetEmojiTexture.OpenMouth,
	[":O"] = GetEmojiTexture.OpenMouth,
	[":%-0"] = GetEmojiTexture.OpenMouth,
	[":P"] = GetEmojiTexture.StuckOutTongue,
	[":%-P"] = GetEmojiTexture.StuckOutTongue,
	[":p"] = GetEmojiTexture.StuckOutTongue,
	[":%-p"] = GetEmojiTexture.StuckOutTongue,
	["=P"] = GetEmojiTexture.StuckOutTongue,
	["=p"] = GetEmojiTexture.StuckOutTongue,
	[";%-p"] = GetEmojiTexture.StuckOutTongueClosedEyes,
	[";p"] = GetEmojiTexture.StuckOutTongueClosedEyes,
	[";P"] = GetEmojiTexture.StuckOutTongueClosedEyes,
	[";%-P"] = GetEmojiTexture.StuckOutTongueClosedEyes,
	[";%-%)"] = GetEmojiTexture.Wink,
	[";%)"] = GetEmojiTexture.Wink,
	[":S"] = GetEmojiTexture.Smirk,
	[":%-S"] = GetEmojiTexture.Smirk,
	[":,%("] = GetEmojiTexture.Cry,
	[":,%-%("] = GetEmojiTexture.Cry,
	[":'%("] = GetEmojiTexture.Cry,
	[":'%-%("] = GetEmojiTexture.Cry,
	[":F"] = GetEmojiTexture.MiddleFinger,
	["</3"] = GetEmojiTexture.BrokenHeart,
	["<3"] = GetEmojiTexture.Heart,
	["♥"] = GetEmojiTexture.Heart,
}
